name: BuildPWS
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  PowerShellDemo:
    name: "PowerShell Demo"
    runs-on: ubuntu-latest

    steps:
      - name: Build Module
        shell: pwsh
        run: |
          Write-Host "File example.txt"
